apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: mp-ambulance-ufe-content
spec:
  microFrontend: mp-ambulance-ufe
  element: mp-ambulance-wl-app
  attributes:
    - name: base-path
      value: /mp-ambulance-wl/
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?mp-ambulance-wl(/.*)?$"
