name: Ambulance uFE CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ambulance-ufe/package-lock.json
    - run: npm ci
      working-directory: ambulance-ufe
    - run: npm run build --if-present
      working-directory: ambulance-ufe
    - run: npm test
      working-directory: ambulance-ufe
